server:
  port: 8080
  servlet:
    context-path: /forum

spring:
  application:
    name: forum-api
  profiles:
    active: develop
  datasource:
    url: jdbc:h2:mem:forumdb;init=create schema if not exists forumdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: forumdb
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration

feign:
  jsonplaceholder:
    name: JSON-PLACEHOLDER
    url: https://jsonplaceholder.typicode.com/
    resource:
      users: users
      photos: photos
      albums: albums
      comments: comments
      posts: posts

test:
  non-updatable-property: fixed value 3 from develop
  updatable-property: v3 from develop
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
